apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: advance-appset
  namespace: argocd
spec:
  generators:
    - matrix:
        generators:
          # Generator 1: Environments
          - list:
              elements:
                - env: dev
                  namespace: dev
                - env: staging
                  namespace: staging
                - env: prod
                  namespace: prod

          # Generator 2: Apps from app-config.json
          - git:
              repoURL: https://github.com/rizwanawsgit/my-k8s-apps.git
              revision: HEAD
              files:
                - path: "manifests/**/app-config.json"

  # Filter - env check karo app-config.json se
  template:
    metadata:
      name: "{{app}}-{{env}}"
      annotations:
        environments: "{{environments}}"
    spec:
      project: default
      source:
        repoURL: https://github.com/rizwanawsgit/my-k8s-apps.git
        targetRevision: HEAD
        path: "manifests/{{app}}"
        helm:
          valueFiles:
            - values.yaml
            - "values-{{env}}.yaml"
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{namespace}}"
      ignoreApplications:
        - name: "{{app}}-{{env}}"
          when: "{{env}} notin {{environments}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true

  syncPolicy:
    preserveResourcesOnDeletion: true