apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: prod-appset
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/rizwanawsgit/argocd-applicationset-advance-setup.git
        revision: HEAD
        directories:
          - path: "manifests/*"   # Sab apps including redis! ✅
  template:
    metadata:
      name: "{{path.basename}}-prod"
    spec:
      project: default
      source:
        repoURL: https://github.com/rizwanawsgit/argocd-applicationset-advance-setup.git
        targetRevision: HEAD
        path: "{{path}}"
        helm:
          valueFiles:
            - values.yaml
            - values-prod.yaml
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{path.basename}}-prod"
      syncPolicy:
        automated:
          prune: false      # Prod mein manual! ✅
          selfHeal: false   # Accidental change nahi ✅
        syncOptions:
          - CreateNamespace=true